### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: 'tgcf.config.yml' when doing docker run

### ISSUE THREAD

**Issue by manojsitapara** [aahnik/tgcf#186]
**Describe the bug**
When running docker container with following command, it throws following error

```shell
INFO:telethon.crypto.libssl:Failed to load SSL library: <class 'OSError'> (no library called "ssl" found)
INFO:root:tgcf.config.yml detected.
Traceback (most recent call last):
  File "/venv/bin/tgcf", line 8, in <module>
    sys.exit(app())
  File "/venv/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/venv/lib/python3.9/site-packages/tgcf/cli.py", line 81, in main
    from tgcf.live import start_sync  # pylint: disable=import-outside-toplevel
  File "/venv/lib/python3.9/site-packages/tgcf/live.py", line 9, in <module>
    from tgcf import config, const
  File "/venv/lib/python3.9/site-packages/tgcf/config.py", line 148, in <module>
    CONFIG = read_config()
  File "/venv/lib/python3.9/site-packages/tgcf/config.py", line 94, in read_config
    with open(CONFIG_FILE_NAME) as file:
IsADirectoryError: [Errno 21] Is a directory: 'tgcf.config.yml'
```

**To Reproduce**
docker run -v tgcf.config.yml:/app/tgcf.config.yml -d --env-file .env aahnik/tgcf

**System information:**
Windows

After google this error, I tried following command, it started running but not forwarding messages

`docker run -v tgcf.config.yml:/app/ -d --env-file .env aahnik/tgcf:minimal`

**Comment by manojsitapara** [comment]
After google this error, I tried following command, it started running but not forwarding messages

`docker run -v tgcf.config.yml:/app/ -d --env-file .env aahnik/tgcf:minimal`
