### ISSUE TITLE
"Async with" outside async function

### ISSUE THREAD

**Issue by Reddog176** [aahnik/tgcf#46]
Run fails with "async with" error. 

```shell
Traceback (most recent call last):
  File "forwarder.py", line 6, in <module>
    from telethon.tl.patched import MessageService
  File "/home/chrisc/telegram-chat-forward/telethon.py", line 24
    async with client:
    ^
SyntaxError: 'async with' outside async function
```

using python 3.7

**Comment by aahnik** [comment]
Hi @Reddog176 you are using some old version of my code. (line 24 does not even have that) Please use the latest version from the main branch.
