### ISSUE TITLE
AttributeError: module 'streamlit' has no attribute 'experimental_rerun'

### ISSUE THREAD

**Issue by urbenx** [aahnik/tgcf#630]
When I try to run the script I get this, any solutions?:

**File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tgcf\web_ui\pages\5_🏃_Run.py", line 102, in <module>
    st.experimental_rerun()
    ^^^^^^^^^^^^^^^^^^^^^**

**Comment by ferelking242** [comment]
i have the same problem please help

AttributeError: module 'streamlit' has no attribute 'experimental_rerun'
Traceback:
File "C:\Users\Admin\my-tgcf\.venv\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
File "C:\Users\Admin\my-tgcf\.venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "C:\Users\Admin\my-tgcf\.venv\Lib\site-packages\tgcf\web_ui\pages\3_🔗_Connections.py", line 112, in <module>
    st.experimental_rerun()

**Comment by JorgaWetzel** [comment]
Same here:

File "C:\Temp\my-tgcf\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "C:\Temp\my-tgcf\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "C:\Temp\my-tgcf\.venv\Lib\site-packages\tgcf\web_ui\pages\5_🏃_Run.py", line 102, in <module>
    st.experimental_rerun()
    ^^^^^^^^^^^^^^^^^^^^^

**Comment by kpbll** [comment]
+1

**Comment by s0ldi3r4** [comment]
+1

**Comment by storm1637** [comment]
(.venv) @:~/tgcf$ tgcf-web
Traceback (most recent call last):
  File "/home//tgcf/.venv/bin/tgcf-web", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home//tgcf/.venv/lib/python3.12/site-packages/tgcf/web_ui/run.py", line 8, in main
    package_dir = resources.path(package=wu, resource="").__enter__()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/resources/_legacy.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/resources/_legacy.py", line 120, in path
    return _common.as_file(_common.files(package) / normalize_path(resource))
                           ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/importlib/resources/abc.py", line 133, in __truediv__
    return self.joinpath(child)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/resources/readers.py", line 92, in joinpath
    return super().joinpath(*descendants)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/resources/abc.py", line 117, in joinpath
    target = next(names)
             ^^^^^^^^^^^
StopIteration

**Comment by storm1637** [comment]
+1 Getting the same error running Python 3.10 in Ubuntu 24.04

2024-12-22 14:12:41.969 Uncaught app execution
Traceback (most recent call last):
  File "/home//my-tgcf/.venv/lib/python3.10/site-packages/tgcf/web_ui/pages/5_🏃_Run.py", line 68, in <module>
    os.kill(CONFIG.pid, signal.SIGCONT)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home//my-tgcf/.venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/home//my-tgcf/.venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/home//my-tgcf/.venv/lib/python3.10/site-packages/tgcf/web_ui/pages/5_🏃_Run.py", line 75, in <module>
    st.experimental_rerun()
AttributeError: module 'streamlit' has no attribute 'experimental_rerun'

**Comment by wfreq** [comment]
ran into this as well, it needs a lesser verison of steamlit to work as that specific command is no longer in steamlit >1.37.0

run
pip uninstall steamlit
pip install steamlit==1.17.0
pip install "altair<5"

**Comment by storm1637** [comment]
> ran into this as well, it needs a lesser verison of steamlit to work as that specific command is no longer in steamlit >1.37.0
> 
> run pip uninstall steamlit pip install steamlit==1.17.0 pip install "altair<5"

This was helpful advice though it's streamlit instead of steamlit. Running these commands fixed the errors I was getting though unfortunately it isn't forwarding anything even though I'm very confident I have everything configured correctly. I tried both the user as the bot forwarding option. Both aren't working with two basic test channels. I think this program has had it's time.

**Comment by ferelking242** [comment]
> ran into this as well, it needs a lesser verison of steamlit to work as that specific command is no longer in steamlit >1.37.0
> 
> run pip uninstall steamlit pip install steamlit==1.17.0 pip install "altair<5"

Ça marche pas qui a une solution

**Comment by ferelking242** [comment]
> > ran into this as well, it needs a lesser verison of steamlit to work as that specific command is no longer in steamlit >1.37.0
> > run pip uninstall steamlit pip install steamlit==1.17.0 pip install "altair<5"
> 
> This was helpful advice though it's streamlit instead of steamlit. Running these commands fixed the errors I was getting though unfortunately it isn't forwarding anything even though I'm very confident I have everything configured correctly. I tried both the user as the bot forwarding option. Both aren't working with two basic test channels. I think this program has had it's time.

I have the same problème do you have a solution

**Comment by NathajiM** [comment]
I fixed this by stopping the UI, changing all instances in the code from st.experimental_rerun to st.rerun, and then running it again. If you bump into the issue again on the run page just do the same thing in the run page code. The error gives you the location of the issue in the files. 
If you made some other changes you may need to run pip install tgcf again too.

Also keep in mind you need to press run and have it running for the bot to work.

**Comment by ferelking242** [comment]
> I fixed this by stopping the UI, changing all instances in the code from st.experimental_rerun to st.rerun, and then running it again. If you bump into the issue again on the run page just do the same thing in the run page code. The error gives you the location of the issue in the files. If you made some other changes you may need to run pip install tgcf again too.
> 
> Also keep in mind you need to press run and have it running for the bot to work.

pls ho can i do it ? https://t.me/FK_MASTER1 my telegram

**Comment by 1k-7** [comment]
For anyone wondering how to solve this error. (windows running wsl)
Simply go to file manager the to linux section (near this pc)
Navigate through the path shown before error msg 
For example if the following is shown 

Traceback (most recent call last):
File "/home//my-tgcf/.venv/lib/python3.10/site-packages/tgcf/web_ui/pages/5_🏃_Run.py", line 68, in
os.kill(CONFIG.pid, signal.SIGCONT)
ProcessLookupError: [Errno 3] No such process

**Make sure ui is stopped before making the below changes**
In linux section go to home, then my-tgcf, then .venv, etc...
Follow path until you see 6 or so *.py files.
Modify run.py,connections.py and plugins.py by opening in notepad or any other plain-text editor
Replace st.experimental_rerun with st.rerun
save file from files section or hit ctrl+s
Do this from the three files mentioned.
Run tgcf-web in environment var again
It should work
