### ISSUE TITLE
Errors when running the start command ubuntu 24.04

### ISSUE THREAD

**Issue by storm1637** [aahnik/tgcf#631]
(.venv) @:~/tgcf$ tgcf-web
Traceback (most recent call last):
File "/home//tgcf/.venv/bin/tgcf-web", line 8, in
sys.exit(main())
^^^^^^
File "/home//tgcf/.venv/lib/python3.12/site-packages/tgcf/web_ui/run.py", line 8, in main
package_dir = resources.path(package=wu, resource="").enter()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/importlib/resources/_legacy.py", line 25, in wrapper
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/importlib/resources/_legacy.py", line 120, in path
return _common.as_file(_common.files(package) / normalize_path(resource))
~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
File "/usr/lib/python3.12/importlib/resources/abc.py", line 133, in truediv
return self.joinpath(child)
^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/importlib/resources/readers.py", line 92, in joinpath
return super().joinpath(*descendants)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/importlib/resources/abc.py", line 117, in joinpath
target = next(names)
^^^^^^^^^^^
StopIteration

**Comment by Ranieeery** [comment]
+1

**Comment by denizkoele** [comment]
Same error
